import { Product } from "./types";

export const mockProducts: Product[] = [
  // 1. BOLOS DE FESTA
  {
    id: "p1_ninho_morango",
    categoryId: "bolos-de-festa",
    name: "Bolo Ninho c/ Morango",
    slug: "bolo-de-festa",
    shortDescription: "O campeão de vendas! Leite Ninho com morangos frescos e mousse leve.",
    description: "Leite Ninho com morangos frescos e mousse de Leite Ninho finalizado com chocolate branco. Escolha o peso (kg), formato e decoração.",
    basePrice: 94.90,
    priceType: "starting_at",
    unit: "kg",
    weight: "A partir de 1kg",
    imageUrl: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p1_brigadeiro",
    categoryId: "bolos-de-festa",
    name: "Bolo de Brigadeiro Gourmet",
    slug: "bolo-de-festa",
    shortDescription: "Massa molhadinha de chocolate com recheio cremoso de brigadeiro puro.",
    description: "O clássico imperdível. Brigadeiro tradicional cremoso com granulado nobre ou raspas de chocolate.",
    basePrice: 89.90,
    priceType: "starting_at",
    unit: "kg",
    weight: "A partir de 1kg",
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p1_alpino",
    categoryId: "bolos-de-festa",
    name: "Bolo Alpino",
    slug: "bolo-de-festa",
    shortDescription: "Mistura perfeita de doce de leite, chocolate meio amargo e Alpino.",
    description: "Massa de chocolate com recheio de creme Alpino, doce de leite e pedaços de chocolate Alpino.",
    basePrice: 89.90,
    priceType: "starting_at",
    unit: "kg",
    weight: "A partir de 1kg",
    imageUrl: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p1_abacaxi_coco",
    categoryId: "bolos-de-festa",
    name: "Bolo Abacaxi c/ Coco",
    slug: "bolo-de-festa",
    shortDescription: "Abacaxi cozido artesanal com coco ralado fresco e creme suave.",
    description: "Recheio suave de creme de baunilha com pedaços de abacaxi e coco umedecido.",
    basePrice: 89.90,
    priceType: "starting_at",
    unit: "kg",
    weight: "A partir de 1kg",
    imageUrl: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p1_ferrero",
    categoryId: "bolos-de-festa",
    name: "Bolo Ferrero Rocher",
    slug: "bolo-de-festa",
    shortDescription: "Nutella cremosa, creme trufado e avelãs crocantes.",
    description: "Super recheio de Nutella com trufado de chocolate e crocante de avelã.",
    basePrice: 94.90,
    priceType: "starting_at",
    unit: "kg",
    weight: "A partir de 1kg",
    imageUrl: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p1_custom",
    categoryId: "bolos-de-festa",
    name: "Monte seu Bolo (100% Personalizado)",
    slug: "bolo-de-festa",
    shortDescription: "Escolha qualquer um dos 55+ sabores, peso, formato e decoração.",
    description: "Monte o bolo exatamente como deseja selecionando entre todos os sabores disponíveis no cardápio.",
    basePrice: 89.90,
    priceType: "starting_at",
    unit: "kg",
    weight: "A partir de 1kg",
    imageUrl: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?auto=format&fit=crop&w=800&q=80",
  },

  // 2. DOCES
  {
    id: "p2",
    categoryId: "doces",
    name: "Doces Tradicionais",
    slug: "doces-tradicionais",
    shortDescription: "Brigadeiro, Beijinho, Cajuzinho, Churros, Bicho de pé e mais.",
    description: "100 uni por R$ 116,00 (ou R$ 1,40 a unidade avulsa). Peso aproximado: 18g.",
    basePrice: 1.40,
    priceType: "per_unit",
    unit: "unidade",
    weight: "18g",
    imageUrl: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p3",
    categoryId: "doces",
    name: "Doces Especiais",
    slug: "doces-especiais",
    shortDescription: "Brigadeiro c/ Nutella, Ninho c/ Uva, Oreo, Confete e mais.",
    description: "100 uni por R$ 145,00 (ou R$ 1,70 a unidade avulsa). Peso aproximado: 18g.",
    basePrice: 1.70,
    priceType: "per_unit",
    unit: "unidade",
    weight: "18g",
    imageUrl: "https://images.unsplash.com/photo-1599785209707-a456fc1337cc?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p2_caixa",
    categoryId: "doces",
    name: "Caixa Degustação Tradicionais (25 uni)",
    slug: "doces-tradicionais",
    shortDescription: "Caixa mista com 25 docinhos tradicionais sortidos.",
    description: "Ideal para pequenas reuniões ou para saborear em família. Inclui brigadeiro, beijinho, cajuzinho e bicho de pé.",
    basePrice: 35.00,
    priceType: "fixed",
    unit: "caixa",
    weight: "450g",
    imageUrl: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p3_caixa",
    categoryId: "doces",
    name: "Caixa Degustação Especiais (25 uni)",
    slug: "doces-especiais",
    shortDescription: "Caixa mista com 25 docinhos gourmet especiais sortidos.",
    description: "Combinação premium com Brigadeiro c/ Nutella, Ninho c/ Uva, Oreo e Maracujá c/ Nutella.",
    basePrice: 42.50,
    priceType: "fixed",
    unit: "caixa",
    weight: "450g",
    imageUrl: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=800&q=80",
  },

  // 3. SALGADOS
  {
    id: "p4",
    categoryId: "salgados",
    name: "Salgados Fritos (Prontos)",
    slug: "salgados-fritos",
    shortDescription: "Coxinha, Bolinho de Queijo, Kibe, Rissoles, Milho c/ Catupiry.",
    description: "Prontos para consumo (40g). 50 uni = R$ 58,00 | 100 uni = R$ 116,00 (ou R$ 1,40/uni avulso).",
    basePrice: 1.40,
    priceType: "per_unit",
    unit: "unidade",
    weight: "40g",
    imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p5",
    categoryId: "salgados",
    name: "Salgados Assados (Prontos)",
    slug: "salgados-assados",
    shortDescription: "Esfihas, Empadas, Enrolado de Salsicha, Bauru.",
    description: "Prontos para consumo (40g). 50 uni = R$ 58,00 | 100 uni = R$ 116,00 (ou R$ 1,40/uni avulso).",
    basePrice: 1.40,
    priceType: "per_unit",
    unit: "unidade",
    weight: "40g",
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p6",
    categoryId: "salgados",
    name: "Salgados Congelados",
    slug: "salgados-congelados",
    shortDescription: "Para fritar ou assar em casa. Variedade completa de sabores.",
    description: "Congelados (40g). 25 uni = R$ 27,00 | 50 uni = R$ 53,00.",
    basePrice: 1.08,
    priceType: "per_unit",
    unit: "unidade",
    weight: "40g",
    imageUrl: "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p4_coxinha",
    categoryId: "salgados",
    name: "Cento de Coxinha de Frango (100 uni)",
    slug: "salgados-fritos",
    shortDescription: "Coxinhas de frango desfiado com tempero especial da casa.",
    description: "Fritas na hora, sequinhas e crocantes. 100 unidades por R$ 116,00.",
    basePrice: 116.00,
    priceType: "fixed",
    unit: "cento",
    weight: "4kg",
    imageUrl: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
  },

  // 4. KITS FESTA
  {
    id: "p7",
    categoryId: "kits-festa",
    name: "Kit 1 (Serve 5 a 7 pessoas)",
    slug: "kit-1",
    shortDescription: "1kg de bolo + 50 Salgados + 25 docinhos.",
    description: "Kit completo para pequenas comemorações em família.",
    basePrice: 178.70,
    priceType: "bundle",
    unit: "kit",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p8",
    categoryId: "kits-festa",
    name: "Kit 2 (Serve até 15 pessoas)",
    slug: "kit-2",
    shortDescription: "2kg de bolo + 100 Salgados + 50 docinhos.",
    description: "Ideal para festas de aniversário médias.",
    basePrice: 349.70,
    priceType: "bundle",
    unit: "kit",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p9",
    categoryId: "kits-festa",
    name: "Kit 3 (Serve até 25 pessoas)",
    slug: "kit-3",
    shortDescription: "3kg de bolo + 200 Salgados + 100 docinhos.",
    description: "Festa completa para reunir todos os amigos e família.",
    basePrice: 599.70,
    priceType: "bundle",
    unit: "kit",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p10",
    categoryId: "kits-festa",
    name: "Kit 4 (Serve até 35 pessoas)",
    slug: "kit-4",
    shortDescription: "4kg de bolo + 250 Salgados + 125 docinhos.",
    description: "Grande comemoração com fartura de doces, salgados e bolo.",
    basePrice: 778.70,
    priceType: "bundle",
    unit: "kit",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p11",
    categoryId: "kits-festa",
    name: "Festa na Caixa",
    slug: "festa-na-caixa",
    shortDescription: "1kg de bolo + 20 Salgados + 12 Docinhos + 2 Bebidas lata.",
    description: "Surpresa perfeita para presentear quem você ama!",
    basePrice: 149.90,
    priceType: "bundle",
    unit: "caixa",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p12",
    categoryId: "kits-festa",
    name: "Caixa Mimo",
    slug: "caixa-mimo",
    shortDescription: "1 mini bolo de festa + 10 Salgados + 4 Docinhos + 1 Bebida lata.",
    description: "Um carinho em formato de presente delicioso.",
    basePrice: 68.00,
    priceType: "bundle",
    unit: "caixa",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p13",
    categoryId: "kits-festa",
    name: "Kit Escola",
    slug: "kit-escola",
    shortDescription: "Fatia de bolo 100g + 1 Fini + 2 Docinhos + 4 Salgados + 1 Suco 200ml.",
    description: "Individual para festinhas escolares (Mínimo de 10 unidades).",
    basePrice: 22.90,
    priceType: "bundle",
    unit: "unidade",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80",
  },

  // 5. BOLOS CASEIROS
  {
    id: "p14",
    categoryId: "bolos-caseiros",
    name: "Bolo Caseiro de Aipim Cremoso",
    slug: "bolo-caseiro-aipim",
    shortDescription: "Fresco, fofinho e com sabor autêntico de casa de vó.",
    description: "Feito diariamente com mandioca fresca selecionada e coco ralado. Perfeito quentinho com café.",
    basePrice: 29.90,
    priceType: "fixed",
    unit: "unidade",
    weight: "Aprox. 800g",
    imageUrl: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p15",
    categoryId: "bolos-caseiros",
    name: "Bolo Caseiro de Banana com Canela",
    slug: "bolo-caseiro-banana",
    shortDescription: "Massa leve, pedaços generosos de banana e toque de canela.",
    description: "Receita afetiva com bananas maduras caramelizadas e canela em pó polvilhada.",
    basePrice: 27.90,
    priceType: "fixed",
    unit: "unidade",
    weight: "Aprox. 750g",
    imageUrl: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p16",
    categoryId: "bolos-caseiros",
    name: "Bolo Caseiro de Cenoura Simples",
    slug: "bolo-caseiro-cenoura-simples",
    shortDescription: "O clássico bolo de cenoura caseiro fofinho e dourado.",
    description: "Massa fofinha feita com cenouras frescas selecionadas. Excelente para o café da tarde.",
    basePrice: 23.90,
    priceType: "fixed",
    unit: "unidade",
    weight: "Aprox. 700g",
    imageUrl: "https://images.unsplash.com/photo-1621236378699-8597faf6a145?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p17",
    categoryId: "bolos-caseiros",
    name: "Bolo de Cenoura c/ Calda Vulcão de Chocolate",
    slug: "bolo-caseiro-cenoura-calda",
    shortDescription: "Cobertura farta e cremosa de brigadeiro gourmet belga.",
    description: "O mais pedido da confeitaria! Massa artesanal de cenoura transbordando em calda cremosa de brigadeiro.",
    basePrice: 34.90,
    priceType: "fixed",
    unit: "unidade",
    weight: "Aprox. 950g",
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p18_fuba",
    categoryId: "bolos-caseiros",
    name: "Bolo de Fubá Cremoso c/ Goiabada",
    slug: "bolo-caseiro-fuba-goiabada",
    shortDescription: "Massa úmida e fofinha com cubinhos derretidos de goiabada cascão.",
    description: "Clássico brasileiro feito com fubá mimoso e pedaços de goiabada cascão que derretem na massa.",
    basePrice: 28.90,
    priceType: "fixed",
    unit: "unidade",
    weight: "Aprox. 800g",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p19_churros",
    categoryId: "bolos-caseiros",
    name: "Bolo Caseiro de Churros c/ Doce de Leite",
    slug: "bolo-caseiro-churros",
    shortDescription: "Massa amanteigada de canela coberta com doce de leite cremoso.",
    description: "Massa aromática com canela e açúcar refinado, finalizada com farta camada de doce de leite artesanal.",
    basePrice: 32.90,
    priceType: "fixed",
    unit: "unidade",
    weight: "Aprox. 850g",
    imageUrl: "https://images.unsplash.com/photo-1550617931-e17a7b70dce2?auto=format&fit=crop&w=800&q=80",
  },

  // 6. TORTAS GOURMET
  {
    id: "p34",
    categoryId: "tortas",
    name: "Torta Alpino",
    slug: "torta-alpino",
    shortDescription: "Fatia R$ 18,90 | Inteira R$ 169,00 (Serve 16 a 20 fatias)",
    description: "Uma mistura equilibrada de doce de leite suave, chocolate meio amargo nobre e pedaços generosos de bombom Alpino.",
    basePrice: 18.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "Aprox. 2.8kg (inteira)",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p35",
    categoryId: "tortas",
    name: "Torta Banoffee Tradicional",
    slug: "torta-banoffe",
    shortDescription: "Fatia R$ 18,90 | Inteira R$ 169,00 (Serve 16 a 20 fatias)",
    description: "Base crocante amanteigada, doce de leite cremoso artesanal, camadas de banana fatiada fresca e chantilly suave com canela.",
    basePrice: 18.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "Aprox. 2.8kg (inteira)",
    imageUrl: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p36",
    categoryId: "tortas",
    name: "Torta Bombom de Uva",
    slug: "torta-bombom-de-uva",
    shortDescription: "Fatia R$ 18,90 | Inteira R$ 169,00 (Serve 16 a 20 fatias)",
    description: "Brigadeiro cremoso de Leite Ninho com uvas verdes Thompson sem sementes, coberto com mousse aveludada de chocolate meio amargo.",
    basePrice: 18.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "Aprox. 2.8kg (inteira)",
    imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p37_holandesa",
    categoryId: "tortas",
    name: "Torta Holandesa Clássica",
    slug: "torta-holandesa",
    shortDescription: "Fatia R$ 18,90 | Inteira R$ 169,00 (Serve 16 a 20 fatias)",
    description: "Clássica coroa de biscoitos Calypso com recheio cremoso suave de creme holandês e cobertura espelhada de ganache de chocolate meio amargo.",
    basePrice: 18.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "Aprox. 2.7kg (inteira)",
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p38_limao",
    categoryId: "tortas",
    name: "Torta de Limão c/ Merengue Maçaricado",
    slug: "torta-limao",
    shortDescription: "Fatia R$ 17,90 | Inteira R$ 159,00 (Serve 16 a 20 fatias)",
    description: "Massa crocante que derrete na boca, creme aveludado de limão taiti e cobertura generosa de merengue maçaricado.",
    basePrice: 17.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "Aprox. 2.5kg (inteira)",
    imageUrl: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p39",
    categoryId: "tortas",
    name: "Torta Ferrero Rocher",
    slug: "torta-ferrero",
    shortDescription: "Fatia R$ 18,90 | Inteira R$ 169,00 (Serve 16 a 20 fatias)",
    description: "Base de bolacha de chocolate crocante, super cremoso de Nutella pura, ganache meio amargo e bombons Ferrero Rocher na decoração.",
    basePrice: 18.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "Aprox. 2.8kg (inteira)",
    imageUrl: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p44",
    categoryId: "tortas",
    name: "Torta Pistache Premium",
    slug: "torta-pistache",
    shortDescription: "Fatia R$ 22,90 | Inteira R$ 206,00 (Serve 16 a 20 fatias)",
    description: "Creme aveludado de pasta pura de pistache italiana, trufado de chocolate branco nobre, raspas artesanais e pistaches crocantes.",
    basePrice: 22.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "Aprox. 2.8kg (inteira)",
    imageUrl: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
  },

  // 7. PUDINS ARTESANAIS
  {
    id: "p45",
    categoryId: "pudim",
    name: "Pudim Artesanal Tradicional",
    slug: "pudim-artesanal",
    shortDescription: "Fatia R$ 11,90 | Inteiro R$ 68,00 (1.5kg - Serve 10 a 12 fatias)",
    description: "O clássico mais amado! Textura ultracremosa sem furinhos, extremamente sedoso, acompanhado de calda de caramelo brilhante.",
    basePrice: 11.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "1.5kg (inteiro)",
    imageUrl: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p45_ninho_nutella",
    categoryId: "pudim",
    name: "Pudim de Leite Ninho c/ Nutella",
    slug: "pudim-ninho-nutella",
    shortDescription: "Fatia R$ 14,90 | Inteiro R$ 85,00 (1.5kg - Serve 10 a 12 fatias)",
    description: "Pudim cremosíssimo de Leite Ninho original coberto generosamente com Nutella pura derretida e finalizado com leite em pó.",
    basePrice: 14.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "1.5kg (inteiro)",
    imageUrl: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p45_mini",
    categoryId: "pudim",
    name: "Mini Pudim Individual Gourmet (150g)",
    slug: "mini-pudim",
    shortDescription: "Porção individual perfeita de 150g com muita calda.",
    description: "Tamanho ideal para a sua sobremesa individual diária ou eventos corporativos. Calda de caramelo dourada inconfundível.",
    basePrice: 9.90,
    priceType: "fixed",
    unit: "unidade",
    weight: "150g",
    imageUrl: "https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p45_chocolate",
    categoryId: "pudim",
    name: "Pudim de Chocolate Nobre 50% Cacau",
    slug: "pudim-chocolate",
    shortDescription: "Fatia R$ 13,90 | Inteiro R$ 78,00 (1.5kg - Serve 10 a 12 fatias)",
    description: "Intenso, macio e aveludado, feito com puro cacau e chocolate nobre meio amargo com calda de chocolate acetinada.",
    basePrice: 13.90,
    priceType: "starting_at",
    unit: "fatia",
    weight: "1.5kg (inteiro)",
    imageUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
  },

  // 8. TRAVESSAS ESPECIAIS (SOBREMESAS NA TRAVESSA)
  {
    id: "p46",
    categoryId: "travessas",
    name: "Travessa Surpresa de Morango",
    slug: "travessa-surpresa-morango",
    shortDescription: "Travessa Inteira R$ 97,80 (Serve 8 a 10 pessoas)",
    description: "Camadas generosas de brigadeiro artesanal de Leite Ninho, morangos frescos higienizados e ganache cremosa de chocolate meio amargo.",
    basePrice: 97.80,
    priceType: "fixed",
    unit: "travessa",
    weight: "Aprox. 1.2kg",
    imageUrl: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p47",
    categoryId: "travessas",
    name: "Travessa Surpresa de Uva Verde",
    slug: "travessa-surpresa-uva",
    shortDescription: "Travessa Inteira R$ 97,80 (Serve 8 a 10 pessoas)",
    description: "Brigadeiro cremoso de Leite Ninho com uvas verdes Thompson sem sementes crocantes, cobertas por ganache de chocolate nobre meio amargo.",
    basePrice: 97.80,
    priceType: "fixed",
    unit: "travessa",
    weight: "Aprox. 1.2kg",
    imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p47_bombom",
    categoryId: "travessas",
    name: "Travessa Bombom Aberto de Morango",
    slug: "travessa-bombom-morango",
    shortDescription: "Travessa Inteira R$ 99,90 (Serve 8 a 10 pessoas)",
    description: "Creme suave de baunilha, camada farta de morangos selecionados frescos e cobertura de chocolate blend com raspas artesanais nobres.",
    basePrice: 99.90,
    priceType: "fixed",
    unit: "travessa",
    weight: "Aprox. 1.2kg",
    imageUrl: "https://images.unsplash.com/photo-1582293041079-7814c2f12063?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p47_banoffee",
    categoryId: "travessas",
    name: "Travessa Banoffee Especial",
    slug: "travessa-banoffee",
    shortDescription: "Travessa Inteira R$ 89,90 (Serve 8 a 10 pessoas)",
    description: "Base crocante de biscoito amanteigado, doce de leite artesanal de tacho, bananas frescas fatiadas e chantilly especial com canela e cacau.",
    basePrice: 89.90,
    priceType: "fixed",
    unit: "travessa",
    weight: "Aprox. 1.2kg",
    imageUrl: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p47_maracuja",
    categoryId: "travessas",
    name: "Travessa Maracujá Trufado",
    slug: "travessa-maracuja",
    shortDescription: "Travessa Inteira R$ 94,90 (Serve 8 a 10 pessoas)",
    description: "Mousse aerada de maracujá da fruta combinada com camada aveludada de ganache de chocolate meio amargo e calda espelhada.",
    basePrice: 94.90,
    priceType: "fixed",
    unit: "travessa",
    weight: "Aprox. 1.2kg",
    imageUrl: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80",
  },

  // 9. COMPLETE SUA FESTA (VELAS & ARTIGOS)
  {
    id: "p48",
    categoryId: "descartaveis",
    name: "Vela Super Numerada (0 a 9)",
    slug: "vela-super",
    shortDescription: "Cores: Azul, Branca, Rosa e Dourada.",
    description: "Vela numérica de alta durabilidade e chama limpa para personalizar a idade no bolo de aniversário.",
    basePrice: 4.50,
    priceType: "per_unit",
    unit: "unidade",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p49",
    categoryId: "descartaveis",
    name: "Vela Glitter Numerada (0 a 9)",
    slug: "vela-glitter",
    shortDescription: "Cores: Rose Gold, Dourada e Prata.",
    description: "Vela numérica luxuosa com acabamento impecável em glitter premium para fotos inesquecíveis.",
    basePrice: 6.50,
    priceType: "per_unit",
    unit: "unidade",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p50",
    categoryId: "descartaveis",
    name: "Vela Estrelar Mágica (Pacote c/ 4 uni)",
    slug: "vela-estrelar",
    shortDescription: "Efeito faísca estrelada brilhante.",
    description: "Pacote com 4 unidades de velas faísca que acendem e criam um lindo espetáculo de luz na hora do parabéns.",
    basePrice: 5.00,
    priceType: "fixed",
    unit: "pacote",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p51",
    categoryId: "descartaveis",
    name: "Vela Vulcão Chama Prateada",
    slug: "vela-vulcao",
    shortDescription: "Efeito cascata luminosa de até 40 segundos.",
    description: "Vela tipo vulcão para transformar o momento dos parabéns em um show vibrante e inesquecível.",
    basePrice: 6.50,
    priceType: "per_unit",
    unit: "unidade",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "p52_kit_festa",
    categoryId: "descartaveis",
    name: "Kit Pratinhos & Garfinhos Descartáveis (10 pessoas)",
    slug: "kit-descartaveis",
    shortDescription: "10 pratos de sobremesa reforçados + 10 garfinhos.",
    description: "Praticidade total para a sua comemoração. Pratinhos resistentes e garfinhos brancos ou transparentes.",
    basePrice: 8.50,
    priceType: "fixed",
    unit: "kit",
    weight: null,
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80",
  },
];
